export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
export const ANNOUNCEMENTS_LOADING = 'ANNOUNCEMENTS_LOADING';
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const GET_SLIDES = 'GET_SLIDES';
export const UPDATE_SLIDE = 'UPDATE_SLIDE';
export const ADD_SLIDE = 'ADD_SLIDE';
export const DELETE_SLIDE = 'DELETE_SLIDE';
export const SLIDES_LOADING = 'SLIDES_LOADING';

export const GET_CONTENT = 'GET_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const CONTENT_LOADING = 'CONTENT_LOADING';

export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const CONTACT_LOADING = 'CONTACT_LOADING';

export const GET_INSURANCE = 'GET_INSURANCE';
export const UPDATE_INSURANCE = 'UPDATE_INSURANCE';
export const INSURANCE_LOADING = 'INSURANCE_LOADING';
export const ADD_INSURANCE = 'ADD_INSURANCE';

export const GET_OFFERS = 'GET_OFFERS';
export const ADD_OFFER = 'ADD_OFFER';
export const DELETE_OFFER = 'DELETE_OFFER';
export const OFFERS_LOADING = 'OFFERS_LOADING';
export const UPDATE_OFFER = 'UPDATE_OFFER';

export const GET_PHOTOS = 'GET_PHOTOS';
export const ADD_PHOTO = 'ADD_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const UPDATE_PHOTO = 'UPDATE_PHOTO';


export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';